#!/usr/bin/env python3

# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Generate source-backed MDX snippets for the Fern example pages."""

from __future__ import annotations

import ast
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / "fern" / "snippets" / "generated" / "examples"
GENERATED_MARKER = (
    "{/* Generated by fern/scripts/generate_example_snippets.py. "
    "Edit the canonical source instead. */}"
)
BACKTICK = chr(96)

FULL_FILE_SOURCES = (
    "examples/python/basic_two_peers.py",
    "examples/cpp/nixl_example.cpp",
    "examples/rust/src/single_process_example.rs",
    "examples/cpp/nixl_etcd_example.cpp",
    "examples/python/nixl_gds_example.py",
    "examples/python/telemetry_reader.py",
    "examples/cpp/telemetry_reader.cpp",
)

FUNCTION_SOURCES = (
    "examples/python/remote_storage_example/nixl_p2p_storage_example.py",
    "examples/python/remote_storage_example/nixl_storage_utils/common.py",
)


def slugify(name: str) -> str:
    """Convert a name to a stable path component."""
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def fenced(content: str, source_path: str) -> str:
    """Wrap content in a language-tagged Markdown fence."""
    fence = BACKTICK * 3
    while fence in content:
        fence += BACKTICK
    language = {".cpp": "cpp", ".py": "python", ".rs": "rust"}[Path(source_path).suffix]
    return f"{fence}{language}\n{content.rstrip()}\n{fence}"


def render_snippet(source_path: str, code: str, start: int, end: int) -> str:
    """Render one generated MDX source snippet."""
    source_url = f"https://github.com/ai-dynamo/nixl/blob/main/{source_path}#L{start}"
    if end != start:
        source_url += f"-L{end}"

    return (
        f"{GENERATED_MARKER}\n\n"
        f"[View canonical source]({source_url})\n\n"
        f"{fenced(code, source_path)}\n"
    )


def render_file_snippet(source_path: str) -> str:
    """Render a complete source file as one snippet."""
    source = (REPO_ROOT / source_path).read_text(encoding="utf-8")
    return render_snippet(source_path, source, 1, len(source.splitlines()))


def function_snippets(source_path: str):
    """Yield one snippet for every public top-level function in a file."""
    source = (REPO_ROOT / source_path).read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source, filename=source_path)
    output_dir = OUTPUT_DIR / slugify(Path(source_path).stem)

    for node in tree.body:
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            continue
        if node.name.startswith("_"):
            continue
        if node.end_lineno is None:
            raise RuntimeError(f"No end line available for {source_path}:{node.name}")

        decorator_lines = [decorator.lineno for decorator in node.decorator_list]
        start = min([node.lineno, *decorator_lines])
        end = node.end_lineno
        code = "\n".join(lines[start - 1 : end])
        output = output_dir / f"{slugify(node.name)}.mdx"
        yield output, render_snippet(source_path, code, start, end)


def write_snippet(path: Path, content: str) -> None:
    """Write one generated snippet."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    print(f"Wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    for source in FULL_FILE_SOURCES:
        path = OUTPUT_DIR / f"{slugify(Path(source).name)}.mdx"
        write_snippet(path, render_file_snippet(source))

    for source in FUNCTION_SOURCES:
        for path, content in function_snippets(source):
            write_snippet(path, content)
