# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

proxy_memview_store_unit_test_dep = declare_dependency(
    sources: [
        'proxy_memview_store.cpp',
    ],
    include_directories: [nixl_inc_dirs, gtest_inc_dirs],
)
