# SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

vars: {
  colors: {
    text: "#EEEEEE"
    secondary: "#AAAAAA"
    watch: "#666666"
    notification-contrast: ${colors.notification}
    network: "#6C8EBF"
    controller-stroke: "#AAAAAA"
    external-stroke: "#888888"
    agent-fill: "#1A2A0D"
    supporting-fill: "#222222"
  }
}

...@common
