name: Copyright Checks

on:
  pull_request

jobs:
  copyright-checks:
    runs-on: ubuntu-24.04
    container:
      image: ghcr.io/dynemo-ai/dynemo/helm-tester:0.1.1
      options: --tty
      volumes:
        - ${{ github.workspace }}:/workspace
    permissions:
      contents: read
      packages: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      # Allowlist the mounted source directory
    - name: Add safe directory to git config
      run: git config --global --add safe.directory /workspace  
    - name: Run Copyright Check
      run: pwsh /workspace/.github/workflows/copyright-check.ps1
      env:
        NVBUILD_VERBOSITY: DETAILED
      timeout-minutes: 5
      working-directory: /workspace