name: Python Checks

on: [pull_request]

jobs:
  python-checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 2
    - name: Check for print() calls
      run: |
        ./.ci/scripts/check_prints.sh ./src
        ./.ci/scripts/check_prints.sh ./test
        ./.ci/scripts/check_prints.sh ./benchmark
